spring:
  datasource:
    mysql:
      type: com.alibaba.druid.pool.DruidDataSource
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://127.0.0.1:3306/wei?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
      username: root
      password: $Wlp#327
      druid:
        initial-size: 5 #连接池初始化大小
        min-idle: 2 #最小空闲连接数
        max-active: 5 #最大连接数
        web-stat-filter:
          exclusions: "*.js,*.gif,*.jpg,*.png,*.css,*.ico,/druid/*" #不统计这些请求数据
        stat-view-servlet: #访问监控网页的登录用户名和密码
          login-username: root
          login-password: root
        type: com.alibaba.druid.pool.DruidDataSource
secure:
  ignored:
    urls: #安全路径白名单
      - /**/v2/api-docs
      - /**/*.js
      - /**/*.css
      - /**/*.png
      - /**/*.ico
      - /swagger-ui.html
      - /swagger-resources/**
      - /swagger/**
      - /webjars/springfox-swagger-ui/**
      - /druid/**
      - /actuator/**
      - /sso/**
      - /admin/account/login
      - /admin/account/logout
      - /admin/account/register
jwt:
  tokenHeader: Authorization #JWT存储的请求头
  secret: mall-portal-secret #JWT加解密使用的密钥
  expiration: 604800 #JWT的超期限时间(60*60*24)
  tokenHead: Bearer #JWT负载中拿到开头
store:
  endpoint: http://127.0.0.1:9090/
  accessKey: minioadmin
  secretKey: minioadmin
  bucket: wei-bucket
  region: us-east-1
  path: admin
