server:
  port: 8888
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
spring:
  profiles:
    active: prod #默认为开发环境
  servlet:
    multipart:
      enabled: true
      max-file-size: 500MB
      max-request-size: 500MB
  service:
    core-pool:
      # 核心线程池大小
      core-pool-size: 4
      # 最大核心线程池大小
      maximum-pool-size: 8
      # 空闲线程存活时间秒s
      keep-alive-time: 60
      # 阻塞队列大小
      work-queue-size: 5
mybatis:
  mapper-locations:
    - classpath*:mappers/**/*.xml
# 上传存储配置
upload:
  # 头像类，Logo类
  avatar:
    # 最大1M
    baseDir: /avatar
    maxSize: 1048576
    expire: 7200